import { CampaignAnalyticsRow } from '../types/analytics.types';

/**
 * Development seed data for the Analytics module.
 * All metrics are pre-set as API-returned values — no client-side calculation.
 */
export const DEV_SEED_ANALYTICS: CampaignAnalyticsRow[] = [
    {
        id: 'camp-001',
        campaign_name: 'Spring Collection Launch',
        status: 'sent',
        sent: 12500,
        delivered: 12185,
        open_rate: 34.2,
        click_rate: 8.7,
        unsubscribe_rate: 0.42,
        bounce_rate: 2.52,
        sent_at: '2026-03-12T09:00:00Z',
    },
    {
        id: 'camp-006',
        campaign_name: 'Valentine\'s Day Promo',
        status: 'sent',
        sent: 9800,
        delivered: 9560,
        open_rate: 41.5,
        click_rate: 12.3,
        unsubscribe_rate: 0.18,
        bounce_rate: 2.45,
        sent_at: '2026-02-12T08:00:00Z',
    },
    {
        id: 'camp-007',
        campaign_name: 'New Year Clearance',
        status: 'sent',
        sent: 15200,
        delivered: 14820,
        open_rate: 28.9,
        click_rate: 6.1,
        unsubscribe_rate: 0.55,
        bounce_rate: 2.50,
        sent_at: '2026-01-02T10:00:00Z',
    },
    {
        id: 'camp-004',
        campaign_name: 'VIP Early Access',
        status: 'sending',
        sent: 3400,
        delivered: 3310,
        open_rate: 52.1,
        click_rate: 18.4,
        unsubscribe_rate: 0.09,
        bounce_rate: 2.65,
        sent_at: '2026-04-17T16:00:00Z',
    },
    {
        id: 'camp-008',
        campaign_name: 'Win-Back Series #3',
        status: 'sent',
        sent: 4300,
        delivered: 4100,
        open_rate: 19.6,
        click_rate: 3.2,
        unsubscribe_rate: 1.12,
        bounce_rate: 4.65,
        sent_at: '2026-04-05T14:00:00Z',
    },
    {
        id: 'camp-009',
        campaign_name: 'Product Review Request',
        status: 'sent',
        sent: 6700,
        delivered: 6580,
        open_rate: 25.8,
        click_rate: 5.9,
        unsubscribe_rate: 0.31,
        bounce_rate: 1.79,
        sent_at: '2026-03-28T11:00:00Z',
    },
    {
        id: 'camp-010',
        campaign_name: 'Flash Sale – 24HR Only',
        status: 'sent',
        sent: 18900,
        delivered: 18400,
        open_rate: 38.7,
        click_rate: 14.2,
        unsubscribe_rate: 0.68,
        bounce_rate: 2.65,
        sent_at: '2026-04-10T06:00:00Z',
    },
    {
        id: 'camp-002',
        campaign_name: 'Weekly Newsletter #42',
        status: 'scheduled',
        sent: 0,
        delivered: 0,
        open_rate: 0,
        click_rate: 0,
        unsubscribe_rate: 0,
        bounce_rate: 0,
        sent_at: undefined,
    },
    {
        id: 'camp-011',
        campaign_name: 'Loyalty Program Invite',
        status: 'sent',
        sent: 8200,
        delivered: 8050,
        open_rate: 31.4,
        click_rate: 9.8,
        unsubscribe_rate: 0.22,
        bounce_rate: 1.83,
        sent_at: '2026-03-20T09:30:00Z',
    },
    {
        id: 'camp-005',
        campaign_name: 'Flash Sale Alert',
        status: 'blocked',
        sent: 0,
        delivered: 0,
        open_rate: 0,
        click_rate: 0,
        unsubscribe_rate: 0,
        bounce_rate: 0,
        sent_at: undefined,
    },
];
